FN.Store.UI/Controllers/ContaController.cs
using FN.Store.Domain.Contracts.Repositories;
using FN.Store.Domain.Helpers;
using FN.Store.UI.ViewModels.Conta.Login;
using System.Web.Mvc;
using System.Web.Security;

namespace FN.Store.UI.Controllers
{
    public class ContaController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;

        public ContaController(IUsuarioRepository usuarioRepository)
        {
            _usuarioRepository = usuarioRepository;
        }

        [HttpGet]
        public ActionResult Login(string returnURL)
        {
            var model = new LoginVM
            {
                ReturnURL = returnURL
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Login(LoginVM model)
        {
            var usuario = _usuarioRepository.Get(model.Email);

            if (usuario == null)
                ModelState.AddModelError("Email", "E-mail não foi localizado");
            else
            {
                if (usuario.Senha != model.Senha.Encrypt())
                    ModelState.AddModelError("Senha", "Senha inválida");
            }

            if (ModelState.IsValid)
            {
                FormsAuthentication.SetAuthCookie(model.Email, model.PermanecerLogado);
                if (!string.IsNullOrEmpty(model.ReturnURL) && Url.IsLocalUrl(model.ReturnURL))
                {
                    return Redirect(model.ReturnURL);
                }

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        protected override void Dispose(bool disposing)
        {
        }
    }
}

FN.Store.UI/Controllers/ProdutosController.cs
using FN.Store.Data.EF.Repositories;
using FN.Store.Domain.Contracts.Repositories;
using FN.Store.Domain.Entities;
using FN.Store.UI.ViewModels.Produtos.AddEdit;
using FN.Store.UI.ViewModels.Produtos.AddEdit.Maps;
using FN.Store.UI.ViewModels.Produtos.Index.Maps;
using System.Web.Mvc;

namespace FN.Store.UI.Controllers
{
    [Authorize]
    public class ProdutosController : Controller
    {

        private readonly IProdutoRepository _produtoRepository;
        private readonly ITipoDeProdutoRepository _tipoDeProdutoRepository;

        public ProdutosController(IProdutoRepository produtoRepository, ITipoDeProdutoRepository tipoDeProdutoRepository)
        {
            _produtoRepository = produtoRepository;
            _tipoDeProdutoRepository = tipoDeProdutoRepository;
        }

        public ViewResult Index()
        {
            var produtos = _produtoRepository.Get().ToProdutoIndexVM();

            return View(produtos);
        }

        [HttpGet]
        public ViewResult AddEdit(int? id)
        {
            var produto = new ProdutoAddEditVM();

            if (id != null)
                produto = _produtoRepository.Get((int)id).ToProdutoAddEditVM();

            var tipos = _tipoDeProdutoRepository.Get();
            ViewBag.Tipos = tipos;

            return View(produto);
        }

        [HttpPost]
        public ActionResult AddEdit(ProdutoAddEditVM produtoVM)
        {
            var produto = produtoVM.ToProduto();

            if (ModelState.IsValid)
            {
                if (produto.Id == 0)
                    _produtoRepository.Add(produto);
                else
                    _produtoRepository.Edit(produto);

                return RedirectToAction("Index");
            }

            var tipos = _tipoDeProdutoRepository.Get();
            ViewBag.Tipos = tipos;

            return View(produto);
        }

        public ActionResult DelProd(int id)
        {
            var produto = _produtoRepository.Get(id);

            if (produto == null)
                return HttpNotFound();

            _produtoRepository.Delete(produto);

            return null;
        }

        protected override void Dispose(bool disposing)
        {
        }

    }
}

FN.Store.UI/Controllers/TipoDeProdutoController.cs
using FN.Store.Domain.Contracts.Repositories;
using FN.Store.UI.ViewModels.TipoDeProdutos;
using FN.Store.UI.ViewModels.TipoDeProdutos.Map;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FN.Store.UI.Controllers
{
    public class TipoDeProdutoController : Controller
    {
        private readonly ITipoDeProdutoRepository _tipoDeProdutoRepository;

        public TipoDeProdutoController(ITipoDeProdutoRepository tipoDeProdutoRepository)
        {
            _tipoDeProdutoRepository = tipoDeProdutoRepository;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var tipos = _tipoDeProdutoRepository.Get().ToProdutoIndexVM();
            return View(tipos);
        }

        [HttpGet]
        public ActionResult AddEdit(int? id)
        {
            TipoDeProdutoVM prod = new TipoDeProdutoVM();

            if (id != null)
                prod = _tipoDeProdutoRepository.Get((int)id).ToTipoDeProdutoVM();

            return View(prod);
        }

        [HttpPost]
        public ActionResult AddEdit(TipoDeProdutoVM tipoProdutoVM)
        {
            var tipoProduto = tipoProdutoVM.ToTipoDeProduto();

            if (ModelState.IsValid)
            {
                if (tipoProduto.Id == 0)
                    _tipoDeProdutoRepository.Add(tipoProduto);
                else
                    _tipoDeProdutoRepository.Edit(tipoProduto);

                return RedirectToAction("Index");
            }
            
            return View(tipoProduto);
        }


        [HttpGet]
        public ActionResult AddEditModal(int? id)
        {
            TipoDeProdutoVM prod = new TipoDeProdutoVM();

            if (id != null)
                prod = _tipoDeProdutoRepository.Get((int)id).ToTipoDeProdutoVM();

            return PartialView("_AddEditModalPartial", prod);
        }

        [HttpPost]
        public ActionResult AddEditModal(TipoDeProdutoVM tipoProdutoVM)
        {
            var tipoProduto = tipoProdutoVM.ToTipoDeProduto();

            if (ModelState.IsValid)
            {
                if (tipoProduto.Id == 0)
                    _tipoDeProdutoRepository.Add(tipoProduto);
                else
                    _tipoDeProdutoRepository.Edit(tipoProduto);

                return PartialView("_AddEditModalPartial");
            }

            return PartialView("_AddEditModalPartial", tipoProdutoVM);
        }

        public ActionResult DelProd(int id)
        {
            var produto = _tipoDeProdutoRepository.Get(id);

            if (produto == null)
                return HttpNotFound();

            _tipoDeProdutoRepository.Delete(produto);

            return null;
        }

    }
}

FN.Store.UI/Controllers/UsuariosController.cs
using FN.Store.Domain.Contracts.Repositories;
using FN.Store.UI.ViewModels.Usuarios.AddEdit;
using FN.Store.UI.ViewModels.Usuarios.AddEdit.Map;
using FN.Store.Domain.Helpers;
using FN.Store.UI.ViewModels.Usuarios.Index;
using FN.Store.UI.ViewModels.Usuarios.Index.Map;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FN.Store.UI.Controllers
{
    [Authorize]
    public class UsuariosController:Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;

        public UsuariosController(IUsuarioRepository usuarioRepository)
        {
            _usuarioRepository = usuarioRepository;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var usuario = _usuarioRepository.Get().ToUsuarioIndexVM();
            return View(usuario);
        }

        [HttpGet]
        public ActionResult AddEdit(int? id)
        {
            var usuario = new UsuarioAddEditVM();

            if (id != null)
                usuario = _usuarioRepository.Get((int)id).ToUsuarioAddEditVM();

            return View(usuario);
        }

        [HttpPost]
        public ActionResult AddEdit(UsuarioAddEditVM usuarioVM)
        {
            var produto = usuarioVM.ToUsuario();

            if (ModelState.IsValid)
            {
                if (usuarioVM.Id == 0)
                {
                    produto.Senha = produto.Senha.Encrypt();
                    _usuarioRepository.Add(produto);
                }
                else
                    _usuarioRepository.Edit(produto);

                return RedirectToAction("Index");
            }

            return View(usuarioVM);
        }

        public ActionResult DelProd(int id)
        {
            var usuario = _usuarioRepository.Get(id);

            if (usuario == null)
                return HttpNotFound();

            _usuarioRepository.Delete(usuario);

            return null;
        }
    }
}

FN.Store.UI/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html class="h-100">
<head>
    <meta charset="utf-8">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <link href="~/Content/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/all.min.css" rel="stylesheet" />
    <title>FN Store | @ViewBag.Title</title>
</head>
<body class="d-flex flex-column h-100">

    @Html.Partial("_menu")     

    <div class="container mt-3">
        @RenderBody()
    </div>
    <footer class="footer footer-custom mt-auto py-3 bg-info">
        <div class="container">
            <span class="text-muted">&copy;@DateTime.Now.Year FN Corporation</span>
        </div>
    </footer>

    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    @RenderSection("scripts",false)
</body>
</html>

FN.Store.UI/Views/Shared/_menu.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">FN Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" href="@Url.Action("Index","Home")">Página Inicial</a>
                </li>
                <li class="nav-item dropdown" id="myDropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">  Produto  </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="@Url.Action("Index","Produtos")">Produtos</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="@Url.Action("Index","TipoDeProduto")">Tipo de Produtos</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="@Url.Action("Index","Usuarios")">Usuários</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="@Url.Action("Sobre","Home")">Sobre</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            @User.Identity.Name
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Trocar Senha</a></li>
                            <li><a class="dropdown-item" href="#">Meu Perfil</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="@Url.Action("LogOut","Conta")">LogOut</a></li>
                        </ul>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("Login","Conta")">Efetuar Login</a>
                    </li>
                }
            </ul>

        </div>
    </div>
</nav>